// Shared OTC medical product catalog for the kiosk.
// Loaded as a plain global (PRODUCTS / CATEGORIES) so pages can use it
// with a simple <script> tag, no bundler or network fetch required —
// this has to run fully offline on kiosk hardware.
//
// `shape` drives the illustrated packaging art in product-art.js (bottle,
// box, tube, spray, patch, pack, or test) — there are no product photos
// on the machine, so each item gets a generated packaging illustration
// instead, color-coded by category.
//
// `uses` mirrors the "Uses" section of the item's FDA Drug Facts label
// (what it's for), separate from `instructions` (how/how much to take)
// and `warnings` — this is what powers the AI Assistant's "what is this
// for?" style answers in med-qa.js.

const CATEGORIES = [
  { id: "emergency", label: "Emergency & First Aid", icon: "alert" },
  { id: "pain", label: "Pain Relief", icon: "pill" },
  { id: "coldallergy", label: "Cold & Allergy", icon: "drop" },
  { id: "stomach", label: "Stomach & Digestion", icon: "pill" },
  { id: "wellness", label: "Wellness & Hygiene", icon: "shield" },
];

const PRODUCTS = [
  // ---------- Emergency & First Aid ----------
  {
    id: "bandaid",
    name: "Band-Aid Assorted Bandages",
    category: "emergency",
    slot: "A1",
    icon: "bandage",
    shape: "box",
    price: 2.99,
    dosage: "30 Count Box",
    activeIngredient: null,
    uses: "Covers and protects minor cuts, scrapes, and blisters from dirt and bacteria while they heal.",
    ageRestricted: false,
    inStock: true,
    instructions: "Clean the wound, apply the bandage, and change daily or whenever it gets wet.",
    warnings: "For external use only. Do not apply to deep puncture wounds or animal bites — seek medical care instead.",
    allergyAlert: "Latex-free adhesive.",
    keywords: [
      "cut", "cut myself", "scrape", "scraped", "bandage", "band aid",
      "band-aid", "bleeding a little", "small cut", "blister", "wound",
      "skinned my knee", "scratch",
    ],
  },
  {
    id: "ointment",
    name: "Antibiotic Ointment (OTC)",
    category: "emergency",
    slot: "A2",
    icon: "tube",
    shape: "tube",
    price: 4.49,
    dosage: "1 oz Tube",
    activeIngredient: "Bacitracin Zinc",
    uses: "Helps prevent infection in minor cuts, scrapes, and burns.",
    ageRestricted: false,
    inStock: true,
    instructions: "Apply a thin layer to the affected area 1–3 times daily.",
    warnings: "Stop use and ask a doctor if a rash or irritation develops.",
    allergyAlert: "May cause allergic skin reaction in rare cases.",
    keywords: [
      "ointment", "infection risk", "neosporin", "minor burn", "small burn",
      "scrape infected", "clean a wound",
    ],
  },
  {
    id: "gauze",
    name: "Sterile Gauze Pad & Tape",
    category: "emergency",
    slot: "A3",
    icon: "bandage",
    shape: "box",
    price: 5.99,
    dosage: "5 Pads + Tape Roll",
    activeIngredient: null,
    uses: "Dresses and protects larger wounds that a small bandage can't cover.",
    ageRestricted: false,
    inStock: true,
    instructions: "Apply directly over the wound and secure with the tape.",
    warnings: "Single use only — discard after use. Seek medical attention for wounds that won't stop bleeding.",
    allergyAlert: "None known.",
    keywords: ["gauze", "deep cut", "large wound", "bleeding a little", "dressing", "cut is bigger"],
  },
  {
    id: "coldpack",
    name: "Instant Cold Pack",
    category: "emergency",
    slot: "A4",
    icon: "drop",
    shape: "pack",
    price: 3.49,
    dosage: "1 Single-Use Pack",
    activeIngredient: null,
    uses: "Provides cold therapy to reduce swelling and pain from minor injuries, sprains, and bruises.",
    ageRestricted: false,
    inStock: true,
    instructions: "Squeeze to activate, wrap in a cloth, and apply to the injury for up to 20 minutes.",
    warnings: "Do not apply directly to bare skin or use on open wounds.",
    allergyAlert: "None known.",
    keywords: ["swelling", "sprain", "bruise", "twisted ankle", "injury", "cold pack", "rolled my ankle"],
  },

  // ---------- Pain Relief ----------
  {
    id: "ibuprofen",
    name: "Ibuprofen 200mg",
    category: "pain",
    slot: "B1",
    icon: "pill",
    shape: "bottle",
    price: 6.49,
    dosage: "24 Caplets, 200mg",
    activeIngredient: "Ibuprofen (NSAID)",
    uses: "Temporarily relieves minor aches and pains from headache, muscle ache, backache, minor arthritis pain, menstrual cramps, toothache, and the common cold; temporarily reduces fever.",
    ageRestricted: false,
    inStock: true,
    instructions: "Adults: take 1 caplet every 4–6 hours with food or water. Do not exceed 6 in 24 hours.",
    warnings: "May increase risk of stomach bleeding. Ask a doctor before use if you have stomach problems or take blood thinners.",
    allergyAlert: "Do not use if allergic to aspirin or other NSAIDs.",
    keywords: [
      "headache", "head ache", "head hurts", "my head hurts", "head hurting",
      "head is pounding", "pounding head", "throbbing head", "migraine",
      "pain", "hurts", "hurt", "hurting", "aches", "aching", "sore",
      "ibuprofen", "muscle ache", "body ache", "back pain",
      "cramps", "period pain", "menstrual cramps", "inflammation",
    ],
  },
  {
    id: "acetaminophen",
    name: "Acetaminophen 500mg",
    category: "pain",
    slot: "B2",
    icon: "pill",
    shape: "bottle",
    price: 6.49,
    dosage: "24 Caplets, 500mg",
    activeIngredient: "Acetaminophen",
    uses: "Temporarily relieves minor aches and pains from headache, muscle ache, backache, minor arthritis pain, the common cold, and toothache; temporarily reduces fever.",
    ageRestricted: false,
    inStock: true,
    instructions: "Adults: take 2 caplets every 6 hours as needed. Do not exceed 6 caplets in 24 hours.",
    warnings: "Severe liver damage may occur if taken with other acetaminophen products or with alcohol use.",
    allergyAlert: "None known.",
    keywords: [
      "fever", "temperature", "acetaminophen", "tylenol", "hot", "chills",
      "burning up", "feel feverish", "running a fever",
    ],
  },
  {
    id: "aspirin",
    name: "Aspirin 325mg",
    category: "pain",
    slot: "B3",
    icon: "pill",
    shape: "bottle",
    price: 5.99,
    dosage: "24 Tablets, 325mg",
    activeIngredient: "Aspirin (NSAID)",
    uses: "Temporarily relieves minor aches and pains from headache, muscle ache, minor arthritis pain, and toothache; temporarily reduces fever.",
    ageRestricted: false,
    inStock: true,
    instructions: "Adults: take 1–2 tablets every 4 hours as needed, not to exceed 12 tablets in 24 hours.",
    warnings: "Reye's syndrome warning: do not give to children or teenagers with viral infections.",
    allergyAlert: "Do not use if allergic to NSAIDs.",
    keywords: ["aspirin", "headache", "pain", "fever", "body ache"],
  },
  {
    id: "patch",
    name: "Menthol Pain Relief Patch",
    category: "pain",
    slot: "B4",
    icon: "drop",
    shape: "patch",
    price: 7.99,
    dosage: "4 Patches",
    activeIngredient: "Menthol 5%",
    uses: "Provides temporary relief of minor muscle and joint pain from backache, arthritis, strains, and sprains.",
    ageRestricted: false,
    inStock: true,
    instructions: "Apply one patch to the affected area; leave on for up to 8 hours.",
    warnings: "Do not use with a heating pad. Discontinue if excessive skin irritation occurs.",
    allergyAlert: "None known.",
    keywords: ["muscle pain", "back pain", "sore muscles", "patch", "shoulder pain", "neck pain"],
  },
  {
    id: "periodrelief",
    name: "Period Pain Relief Caplets",
    category: "pain",
    slot: "B5",
    icon: "pill",
    shape: "bottle",
    price: 7.49,
    dosage: "20 Caplets",
    activeIngredient: "Acetaminophen, Pamabrom, Pyrilamine Maleate",
    uses: "Temporarily relieves symptoms associated with premenstrual and menstrual periods, including cramps, bloating, water-weight gain, and headache.",
    ageRestricted: false,
    inStock: true,
    instructions: "Adults: take 2 caplets every 4–6 hours as needed. Do not exceed 8 caplets in 24 hours.",
    warnings: "Contains a diuretic and antihistamine — may cause drowsiness. Ask a doctor before use if you have liver disease.",
    allergyAlert: "None known.",
    keywords: [
      "period cramps", "period pain", "menstrual cramps", "pms", "bloating",
      "period", "cramps", "midol", "menstrual symptoms", "my period hurts",
    ],
  },
  {
    id: "heatpatch",
    name: "Menstrual Heat Patch",
    category: "pain",
    slot: "B6",
    icon: "drop",
    shape: "patch",
    price: 6.99,
    dosage: "3 Patches",
    activeIngredient: null,
    uses: "Provides soothing, low-level heat to help relieve minor muscle and menstrual cramps.",
    ageRestricted: false,
    inStock: true,
    instructions: "Apply directly to lower abdomen or back over clothing. Provides up to 8 hours of soothing heat.",
    warnings: "Do not apply directly to bare skin. Do not use while sleeping.",
    allergyAlert: "None known.",
    keywords: [
      "period cramps", "menstrual cramps", "heat patch", "cramps",
      "lower back pain period", "period pain", "cramping",
    ],
  },

  // ---------- Cold & Allergy ----------
  {
    id: "antihistamine",
    name: "Allergy Relief Antihistamine",
    category: "coldallergy",
    slot: "C1",
    icon: "pill",
    shape: "bottle",
    price: 6.99,
    dosage: "24 Tablets, 25mg",
    activeIngredient: "Diphenhydramine HCl",
    uses: "Temporarily relieves runny nose, sneezing, itchy watery eyes, and itching of the nose or throat from hay fever or other upper respiratory allergies.",
    ageRestricted: false,
    inStock: true,
    instructions: "Adults: take 1–2 tablets every 4–6 hours as needed.",
    warnings: "May cause drowsiness. Do not drive or operate machinery after taking.",
    allergyAlert: "None known.",
    keywords: [
      "allergy", "allergies", "itchy", "itching", "hives", "sneezing",
      "sneeze", "runny nose", "stuffy nose", "hay fever", "rash", "mild rash",
      "benadryl", "watery eyes", "itchy eyes",
    ],
  },
  {
    id: "coughdrops",
    name: "Soothing Cough Drops",
    category: "coldallergy",
    slot: "C2",
    icon: "drop",
    shape: "box",
    price: 3.49,
    dosage: "18 Drops",
    activeIngredient: "Menthol",
    uses: "Temporarily relieves occasional minor throat irritation and coughing due to a cold.",
    ageRestricted: false,
    inStock: true,
    instructions: "Dissolve one drop slowly in the mouth. Repeat as needed.",
    warnings: "Choking hazard for young children — not intended for children under 5.",
    allergyAlert: "None known.",
    keywords: [
      "cough", "coughing", "sore throat", "throat hurts", "my throat hurts",
      "throat", "cold", "scratchy throat", "hoarse",
    ],
  },
  {
    id: "coldflu",
    name: "Daytime Cold & Flu Caplets",
    category: "coldallergy",
    slot: "C3",
    icon: "pill",
    shape: "bottle",
    price: 8.99,
    dosage: "16 Caplets",
    activeIngredient: "Dextromethorphan HBr",
    uses: "Temporarily relieves cough, body aches, headache, and fever associated with the common cold or flu.",
    ageRestricted: true,
    inStock: true,
    instructions: "Adults: take 2 caplets every 6 hours. Do not exceed 8 caplets in 24 hours.",
    warnings: "Contains a cough suppressant restricted for sale to minors in this state — valid ID required.",
    allergyAlert: "None known.",
    keywords: ["cold", "flu", "cough", "congestion", "runny nose", "cold and flu", "body aches with cold"],
  },
  {
    id: "decongestant",
    name: "Nasal Decongestant Spray",
    category: "coldallergy",
    slot: "C4",
    icon: "drop",
    shape: "spray",
    price: 6.99,
    dosage: "0.5 fl oz",
    activeIngredient: "Oxymetazoline HCl",
    uses: "Temporarily relieves nasal congestion from the common cold, hay fever, or other upper respiratory allergies.",
    ageRestricted: false,
    inStock: false,
    instructions: "2–3 sprays per nostril, not more often than every 10–12 hours.",
    warnings: "Do not use for more than 3 days — may cause rebound congestion.",
    allergyAlert: "None known.",
    keywords: ["stuffy nose", "congestion", "blocked nose", "decongestant", "nose is stuffed up"],
  },

  // ---------- Stomach & Digestion ----------
  {
    id: "antacid",
    name: "Antacid Chewables",
    category: "stomach",
    slot: "D1",
    icon: "pill",
    shape: "bottle",
    price: 4.99,
    dosage: "32 Chewables",
    activeIngredient: "Calcium Carbonate",
    uses: "Relieves heartburn, acid indigestion, and upset stomach.",
    ageRestricted: false,
    inStock: true,
    instructions: "Chew 2–4 tablets as symptoms occur.",
    warnings: "Do not take more than 10 tablets in 24 hours.",
    allergyAlert: "None known.",
    keywords: [
      "stomach", "stomach hurts", "my stomach hurts", "heartburn",
      "acid reflux", "indigestion", "nausea", "nauseous", "upset stomach",
      "bloated", "gassy", "stomach ache", "stomachache",
    ],
  },
  {
    id: "electrolyte",
    name: "Electrolyte Rehydration Packet",
    category: "stomach",
    slot: "D2",
    icon: "drop",
    shape: "pack",
    price: 5.49,
    dosage: "6 Packets",
    activeIngredient: "Electrolyte Blend",
    uses: "Helps replace fluids and electrolytes lost from sweating, mild dehydration, or diarrhea.",
    ageRestricted: false,
    inStock: true,
    instructions: "Mix one packet with 16 oz of water and drink.",
    warnings: "Consult a doctor if vomiting or diarrhea lasts more than 24 hours.",
    allergyAlert: "None known.",
    keywords: [
      "dehydrated", "dehydration", "hangover", "electrolyte", "thirsty",
      "dizzy", "lightheaded", "low energy hot day",
    ],
  },
  {
    id: "motionsickness",
    name: "Motion Sickness Tablets",
    category: "stomach",
    slot: "D3",
    icon: "pill",
    shape: "bottle",
    price: 5.99,
    dosage: "8 Tablets",
    activeIngredient: "Dimenhydrinate",
    uses: "Prevents and treats nausea, vomiting, and dizziness from motion sickness.",
    ageRestricted: false,
    inStock: true,
    instructions: "Take 1–2 tablets 30 minutes before travel.",
    warnings: "May cause drowsiness. Avoid alcohol.",
    allergyAlert: "None known.",
    keywords: [
      "motion sickness", "car sick", "carsick", "sea sick", "seasick",
      "nauseous traveling", "dizzy travel", "queasy on the road",
    ],
  },
  {
    id: "antidiarrheal",
    name: "Anti-Diarrheal Caplets",
    category: "stomach",
    slot: "D4",
    icon: "pill",
    shape: "bottle",
    price: 6.49,
    dosage: "12 Caplets",
    activeIngredient: "Loperamide HCl",
    uses: "Controls symptoms of diarrhea, including traveler's diarrhea.",
    ageRestricted: false,
    inStock: true,
    instructions: "Take 2 caplets after the first loose stool, then 1 after each following, up to 4 per day.",
    warnings: "Do not use if you have bloody or black stool without asking a doctor.",
    allergyAlert: "None known.",
    keywords: ["diarrhea", "upset stomach", "stomach bug", "loose stool"],
  },

  // ---------- Wellness & Hygiene ----------
  {
    id: "pads",
    name: "Feminine Hygiene Pads",
    category: "wellness",
    slot: "E1",
    icon: "shield",
    shape: "box",
    price: 5.49,
    dosage: "20 Count, Regular Absorbency",
    activeIngredient: null,
    uses: "For feminine hygiene use during menstruation.",
    ageRestricted: false,
    inStock: true,
    instructions: "Change every 4–6 hours or as needed. Follow package instructions for application.",
    warnings: "For external use only. Discontinue use if irritation occurs.",
    allergyAlert: "None known.",
    keywords: [
      "period", "pads", "sanitary pads", "menstrual pads", "feminine hygiene",
      "my period started", "heavy flow", "period products",
    ],
  },
  {
    id: "tampons",
    name: "Tampons, Regular Absorbency",
    category: "wellness",
    slot: "E5",
    icon: "drop",
    shape: "box",
    price: 6.49,
    dosage: "18 Count, Regular",
    activeIngredient: null,
    uses: "For feminine hygiene use during menstruation.",
    ageRestricted: false,
    inStock: true,
    instructions: "Change every 4–8 hours. Wash hands before and after use. Follow the package insert for insertion instructions.",
    warnings: "Rarely associated with Toxic Shock Syndrome (TSS). Use the lowest absorbency needed and do not leave in for more than 8 hours.",
    allergyAlert: "None known.",
    keywords: ["tampons", "period", "menstrual", "feminine hygiene", "heavy flow", "period products"],
  },
  {
    id: "pregnancytest",
    name: "Pregnancy Test",
    category: "wellness",
    slot: "E2",
    icon: "test",
    shape: "test",
    price: 9.99,
    dosage: "1 Test",
    activeIngredient: null,
    uses: "For home use to detect pregnancy.",
    ageRestricted: false,
    inStock: true,
    instructions: "Test first thing in the morning for the most accurate result. Follow package instructions.",
    warnings: "Consult a doctor to confirm any result.",
    allergyAlert: "None known.",
    keywords: ["pregnancy test", "pregnant", "am i pregnant", "missed period", "could i be pregnant"],
  },
  {
    id: "sanitizer",
    name: "Hand Sanitizer",
    category: "wellness",
    slot: "E3",
    icon: "tube",
    shape: "tube",
    price: 2.99,
    dosage: "2 fl oz",
    activeIngredient: "Ethyl Alcohol 65%",
    uses: "Helps reduce bacteria on skin when soap and water aren't available.",
    ageRestricted: false,
    inStock: true,
    instructions: "Apply to hands and rub until dry.",
    warnings: "Flammable. Keep away from open flame. For external use only.",
    allergyAlert: "None known.",
    keywords: ["sanitizer", "germs", "clean hands", "disinfect", "hand gel"],
  },
  {
    id: "sunscreen",
    name: "Travel Sunscreen SPF 30",
    category: "wellness",
    slot: "E4",
    icon: "drop",
    shape: "tube",
    price: 8.49,
    dosage: "3 fl oz",
    activeIngredient: "Avobenzone / Octisalate",
    uses: "Helps prevent sunburn.",
    ageRestricted: false,
    inStock: true,
    instructions: "Apply generously 15 minutes before sun exposure; reapply every 2 hours.",
    warnings: "For external use only. Avoid contact with eyes.",
    allergyAlert: "None known.",
    keywords: ["sunburn", "sun protection", "sunscreen", "spf", "going to the beach"],
  },
];

// Things this machine can never dispense — surfaces the
// "prescription only / not equipped" response instead of a product.
const PRESCRIPTION_KEYWORDS = [
  "prescription", "antibiotics", "antibiotic pill", "amoxicillin", "insulin",
  "epipen", "epi-pen", "narcotic", "opioid", "oxycodone", "vicodin",
  "xanax", "adderall", "birth control pill", "the pill", "morphine",
  "controlled substance", "inhaler refill", "steroid shot", "prescribed",
];

// Life-threatening language -> full-screen emergency stop.
const EMERGENCY_KEYWORDS = [
  "chest pain", "can't breathe", "cant breathe", "cannot breathe",
  "difficulty breathing", "trouble breathing", "unconscious", "unresponsive",
  "severe bleeding", "heavy bleeding", "bleeding a lot", "won't stop bleeding",
  "overdose", "overdosed", "suicidal", "want to die", "kill myself",
  "seizure", "stroke", "face drooping", "slurred speech", "anaphylaxis",
  "throat closing", "throat is closing", "severe allergic reaction",
  "heart attack", "choking", "poisoned", "poisoning", "not breathing",
];
